language: python
python:
- '2.7'
dist: trusty
services:
- docker
- mysql
before_install:
- sudo apt-get -qq update
- pip install codecov
- pip install pytest-cov
- pip install codacy-coverage
install:
- pip install -r requirements.txt
- pip install .
script:
- PYTHONPATH=./ py.test . --cov=./
after_success:
- coverage xml
- python-codacy-coverage -r coverage.xml
- codecov
